language: rust
cache: cargo
sudo: false

rust:
  - 1.35.0
  - nightly

before_script:
  - rustup component add rustfmt-preview

script:
  - if [ "$TRAVIS_RUST_VERSION" != nightly ]; then cargo fmt --all -- --check; fi
  - cargo build
  - cargo test

# In addition to pull requests, always build these branches
branches:
  only:
    - master
