[package]
name = "hst-core"
version = "0.1.0"
authors = ["Douglas Creager <dcreager@dcreager.net>"]
edition = "2018"

[dependencies]
auto_enums = "0.5"
auto_from = "0.3"

[dev-dependencies]
maplit = "1.0"
proptest = "0.9"
proptest-attr-macro = "0.1"
